<a href="https://colab.research.google.com/github/Aatmaj-Zephyr/Machine-Learning-Lab/blob/main/Exp%206/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data=[[4,8,13,7],[11,4,5,14]]

In [ ]:

#step 1
d = len(data) # Number of features
n = len(data[1]) # Number of Samples



In [ ]:
# step 3
mean = np.mean(data,axis = 1)
assert len(mean) == d

In [ ]:
#funcion to calculate covariance of dimentions d1 and d2

def cov(x,y):
  s=0
  for i in range(n):
    s=s+(mean[x]-data[x][i])*(mean[y]-data[y][i])
  s=s/(n-1)
  return s



In [ ]:
# step 4: calculate covariance matrix
covariance = np.zeros((d,d))
for i in range(d):
  for j in range(d):
    covariance[i][j] = cov(i,j)
covariance

array([[ 14., -11.],
       [-11.,  23.]])

In [ ]:
# step 5 calculate eigenvalue & eigenvector
from numpy.linalg import eig

lambda_1,v= eig(covariance)
print(lambda_1)
print(" ")
print(v)

[ 6.61513568 30.38486432]
 
[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]


In [ ]:
#step 6: select k principle components
k=1
selected_vectors=v[np.argsort(lambda_1)[::-1]] # sort with respect to k
selected_vectors=selected_vectors[:1]
selected_vectors

array([[-0.55738997, -0.83025082]])

In [ ]:
#step 7: calculation of principle component

new_data = selected_vectors@(data-mean.reshape((2,1)))
new_data

array([[ 0.15393283,  3.73612869,  0.11892802, -4.00898954]])